---
title: 'MinerĂ?a de datos: PRA2 - Modelado de un juego de datos'
author: "Autor: Nombre estudiante"
date: "Noviembre 2019"
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 2
    includes:
      in_header: 75.584-PEC-header.html
  word_document: default
  pdf_document:
    highlight: zenburn
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
******
# IntroducciĂłn
******
## PresentaciĂłn
Esta prĂĄctica cubre de forma transversal la asignatura.

Las PrĂĄcticas 1 y 2 de la asignatura se plantean de una forma conjunta de modo que la PrĂĄctica 2 serĂĄ continuaciĂłn de la 1.

El objetivo global de las dos prĂĄcticas consiste en seleccionar uno o varios juegos de datos, realizar las tareas de preparaciĂłn y anĂĄlisis exploratorio con el objetivo de disponer de datos listos para aplicar algoritmos de clustering, asociaciĂłn y clasificaciĂłn.

## Competencias
Las competencias que se trabajan en esta prueba son:  

* Uso y aplicaciĂłn de las TIC en el ĂĄmbito acadĂŠmico y profesional.
* Capacidad para innovar y generar nuevas ideas.
* Capacidad para evaluar soluciones tecnolĂłgicas y elaborar propuestas de proyectos teniendo en cuenta los recursos, las alternativas disponibles y las condiciones de mercado.
* Conocer las tecnologĂ?as de comunicaciones actuales y emergentes asĂ? como saberlas aplicar convenientemente para diseĂąar y desarrollar soluciones basadas en sistemas y tecnologĂ?as de la informaciĂłn.
* AplicaciĂłn de las tĂŠcnicas especĂ?ficas de ingenierĂ?a del software en las diferentes etapas del ciclo de vida de un proyecto.
* Capacidad para aplicar las tĂŠcnicas especĂ?ficas de tratamiento, almacenamiento y administraciĂłn de datos.
* Capacidad para proponer y evaluar diferentes alternativas tecnolĂłgicas para resolver un problema concreto.

## Objetivos
La correcta asimilaciĂłn de todos los aspectos trabajados durante el semestre.  
En esta prĂĄctica abordamos un caso real de minerĂ?a de datos donde tenemos que poner en juego todos los conceptos trabajados.
Hay que trabajar todo el ciclo de vida del proyecto. Desde el objetivo del proyecto hasta la implementaciĂłn del conocimiento encontrado pasando por la preparaciĂłn, limpieza de los datos, conocimiento de los datos, generaciĂłn del modelo, interpretaciĂłn y evaluaciĂłn.

## DescripciĂłn de la PEC a realizar

## Recursos BĂĄsicos
Material docente proporcionado por la UOC. 

## Criterios de valoraciĂłn

**Ejercicios prĂĄcticos** 

Para todas las PEC es necesario documentar en cada apartado del ejercicio prĂĄctico que se ha hecho y como se ha hecho.

## Formato y fecha de entrega
El formato de entrega es: usernameestudiante-PECn.html/doc/docx/odt/pdf  
Fecha de entrega: 15/01/2020  
Se debe entregar la PEC en el buzĂłn de entregas del aula  

## Nota: Propiedad intelectual 

> A menudo es inevitable, al producir una obra multimedia, hacer uso de recursos creados por terceras personas. Es por lo tanto comprensible hacerlo en el marco de una prĂĄctica de los estudios de InformĂĄtica, Multimedia y TelecomunicaciĂłn de la UOC, siempre y cuando esto se documente claramente y no suponga plagio en la prĂĄctica. 

> Por lo tanto, al presentar una prĂĄctica que haga uso de recursos ajenos, se debe presentar junto con ella un documento en que se detallen todos ellos, especificando el nombre de cada recurso, su autor, el lugar donde se obtuvo y su estatus legal: si la obra esta protegida por el copyright o se acoge a alguna otra licencia de uso (Creative Commons, licencia GNU, GPL ...). 
El estudiante deberĂĄ asegurarse de que la licencia no impide especĂ?ficamente su uso en el marco de la prĂĄctica. En caso de no encontrar la informaciĂłn correspondiente tendrĂĄ que asumir que la obra esta protegida por copyright. 

> DeberĂŠis, ademĂĄs, adjuntar los ficheros originales cuando las obras utilizadas sean digitales, y su cĂłdigo fuente si corresponde.  

******
# Enunciado
******
Como continuaciĂłn del estudio iniciado en la prĂĄctica 1, procedemos en esta prĂĄctica 2 a aplicar modelos analĂ?ticos sobe el juego de datos seleccionado y preparado en la prĂĄctica anterior.

De este modo se pide al estudiante que complete los siguientes pasos:  

1. Aplicar un modelo de generaciĂłn de reglas a partir de **ĂĄrboles de decisiĂłn**.  

2. Aplicar un modelo **no supervisado** y basado en el concepto de **distancia**, sobre el juego de datos.   

3. Aplica de nuevo el modelo anterior, pero usando una **mĂŠtrica distinta** y compara los resultados.

4. Aplicar un **modelo supervisado** sobre el juego de datos **sin** haber aplicado previamente **PCA/SVD**.

5. Aplicar un **modelo supervisado** sobre el juego de datos habiendo aplicado previamente **PCA/SVD**.

6. ÂżHa habido mejora en capacidad predictiva, tras aplicar PCA/SVD? ÂżA quĂŠ crees que es debido?.   


******
# RĂşbrica
******
 

* 15%. Se generan reglas y se comentan e interpretan las más significativas. Evaluar la calidad del modelo generado con los indicadores que se consideren adecuados.
* 15%. Se genera modelo no supervisado, se muestran y comentan medidas de calidad del modelo generado y se comentan las conclusiones así como la descripción de los grupos obtenidos.
* 20%. Se genera modelo no supervisado con métrica de distancia distinta al anterior. Se muestran y comentan medidas de calidad del modelo generado y se comentan las conclusiones así como la descripción de los grupos obtenidos. Adicionalmente se comparan los dos modelos no supervisados con métricas de distancia distinta.
* 15%. Se genera un modelo supervisado sin PCA/SVD previo, se muestran y comentan medidas de calidad del modelo generado y se comenta extensamente el conocimiento extraído del modelo.
* 15%. Se genera un modelo supervisado con PCA/SVD previo, se muestran y comentan medidas de calidad del modelo generado y se comenta extensamente el conocimiento extraído del modelo. Se valorará la extracción de conocimiento del modelo generado.
* 20%. Se compara la capacidad predictiva de los dos modelos supervisados y se comenta la diferencia de rendimiento en base al efecto PCA/SVD.








