--USE [DW_DB_loginuoc]
--GO

CREATE TABLE [dbo].[DIM_ANIO](
	[SK_DIM_ANIO] [numeric](4, 0) NOT NULL,
	[DESC_ANIO] [varchar](50) NOT NULL,
 CONSTRAINT [PK_DIM_ANIO] PRIMARY KEY CLUSTERED 
(
	[SK_DIM_ANIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO